# Generated by Django 5.1.7 on 2025-03-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('collection', models.CharField(blank=True, max_length=100, verbose_name='Серия (коллекция)')),
                ('style', models.CharField(blank=True, max_length=100, verbose_name='Стиль')),
                ('body_color', models.CharField(blank=True, max_length=100, verbose_name='Цвет корпуса')),
                ('plafond_color', models.CharField(blank=True, max_length=100, verbose_name='Цвет плафона')),
                ('body_material', models.CharField(blank=True, max_length=255, verbose_name='Материал корпуса')),
                ('plafond_material', models.CharField(blank=True, max_length=255, verbose_name='Материал плафона')),
                ('head_shape', models.CharField(blank=True, max_length=100, verbose_name='Форма головы')),
                ('installation_type', models.CharField(blank=True, max_length=100, verbose_name='Тип установки')),
                ('mounting_type', models.CharField(blank=True, max_length=255, verbose_name='Тип крепления')),
                ('bracket_count', models.IntegerField(blank=True, null=True, verbose_name='Количество кронштейнов')),
                ('lamp_count', models.IntegerField(blank=True, null=True, verbose_name='Количество ламп')),
                ('socket_type', models.CharField(blank=True, max_length=50, verbose_name='Цоколь')),
                ('lamp_type', models.CharField(blank=True, max_length=100, verbose_name='Тип ламп')),
                ('max_power', models.IntegerField(blank=True, null=True, verbose_name='Макс. мощность')),
                ('voltage', models.IntegerField(blank=True, null=True, verbose_name='Напряжение')),
                ('ip_rating', models.CharField(blank=True, max_length=20, verbose_name='Степень защиты IP')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('head_diameter', models.IntegerField(blank=True, null=True, verbose_name='Размер головы')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Длина')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='Глубина')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна производства')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='Гарантия')),
                ('equipment', models.TextField(blank=True, verbose_name='Комплектация')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Прошлая цена')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('main_image', models.ImageField(blank=True, upload_to='lamps/', verbose_name='Основное изображение')),
                ('scheme_image', models.ImageField(blank=True, upload_to='lamps/schemes/', verbose_name='Схема')),
                ('lamp_image', models.ImageField(blank=True, upload_to='lamps/lamp_photos/', verbose_name='Фото ламп')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svet_site.finalsection', verbose_name='Раздел')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('main_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svet_site.mainsection', verbose_name='Основной раздел')),
            ],
        ),
        migrations.AddField(
            model_name='finalsection',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svet_site.subsection', verbose_name='Подраздел'),
        ),
    ]
