# Generated by Django 5.1.7 on 2025-03-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svet_site', '0002_lamp_subsection_alter_lamp_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='max_power',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Макс. мощность'),
        ),
    ]
