# Generated by Django 5.1.7 on 2025-03-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svet_site', '0003_alter_lamp_max_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='bracket_count',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество кронштейнов'),
        ),
    ]
