# Generated by Django 5.1.7 on 2025-03-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svet_site', '0004_alter_lamp_bracket_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='additional_image_1',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Картинка вторая'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_10',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 13'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_11',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 14'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_12',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 15'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_13',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 16'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_14',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 17'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_15',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 18'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_16',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 19'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_17',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 20'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_2',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 5'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_3',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 6'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_4',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 7'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_5',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 8'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_6',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 9'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_7',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 10'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_8',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 11'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='additional_image_9',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Доп фото 12'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='detail_image',
            field=models.ImageField(blank=True, upload_to='lamps/', verbose_name='Детальная картинка'),
        ),
    ]
